#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the OpenMANIPULATOR-P usb connection."
echo ""

sudo cp `ros2 pkg prefix open_manipulator_p_controller --share`/99-open-manipulator-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
